name: 🚀 Publish to pypi

on: workflow_dispatch

permissions:
  contents: read
  id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

jobs:
  publish-pypi:
    uses: ./.github/workflows/publish_template.yml
    with:
      environment-name: "pypi"
      environment-url: "https://pypi.org/p/map_with_stats"
      publish-url: https://upload.pypi.org/legacy/
