name: 🚀🧪 Publish to Test pypi

on:
  push:
    tags: ["*"]

permissions:
  contents: read
  id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

jobs:
  publish-testpypi:
    uses: ./.github/workflows/publish_template.yml
    with:
      environment-name: "testpypi"
      environment-url: "https://test.pypi.org/p/map_with_stats"
      publish-url: https://test.pypi.org/legacy/
